import { Manrope } from 'next/font/google';
import './globals.css';

const manrope = Manrope({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-manrope',
});

export const metadata = {
  title: 'Git Command Test',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html
      lang='en'
      data-theme='dark'
      data-scroll-behavior='smooth'
      suppressHydrationWarning
      className={`${manrope.className}dark`}
    >
      <body className='flex min-h-screen flex-col bg-black antialiased'>
        <main className='grow'>
          <div className='mx-auto max-w-full'>{children}</div>
        </main>
      </body>
    </html>
  );
}
