import { Manrope } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import BlackFriday from '@/components/BlackFriday';

const manrope = Manrope({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-manrope',
});

export const metadata = {
  title: 'Git Command Test',
  description: 'Generated by create najimulhaque',
};

export default function RootLayout({ children }) {
  return (
    <html
      lang='en'
      data-scroll-behavior='smooth'
      suppressHydrationWarning
      className={`${manrope.className}`}
    >
      <body className='flex min-h-screen flex-col  antialiased'>
        <BlackFriday />
        <Navbar />
        <main className='grow'>
          <div className='mx-auto max-w-full'>{children}</div>
        </main>
      </body>
    </html>
  );
}
